-- 020_exercise_ratings_review.sql
-- Applies the 111 reviewed tier / home_friendly answers and clears the
-- needs_tier_review + needs_home_review flags set by migration 019.
-- Keyed on exercises.slug. Idempotent: re-running is a no-op.
-- Paste into Supabase Dashboard -> SQL Editor -> Run.

BEGIN;

UPDATE exercise_ratings r
SET tier = v.tier, home_friendly = v.home_friendly
FROM (VALUES
  ('archer-push-up', 'A', TRUE),
  ('decline-push-up', 'A', TRUE),
  ('dumbbell-pullover', 'B', TRUE),
  ('hindu-push-up', 'B', TRUE),
  ('incline-machine-press', 'A', FALSE),
  ('kettlebell-floor-press', 'B', TRUE),
  ('svend-press', 'B', FALSE),
  ('wide-push-up', 'A', TRUE),
  ('dumbbell-shrug', 'A', TRUE),
  ('inverted-row', 'S', TRUE),
  ('kettlebell-swing', 'A', TRUE),
  ('landmine-row', 'B', FALSE),
  ('neutral-grip-pull-up', 'S', TRUE),
  ('pendlay-row', 'S', FALSE),
  ('prone-y-raise', 'B', TRUE),
  ('rack-pull', 'B', FALSE),
  ('reverse-grip-lat-pulldown', 'A', FALSE),
  ('seal-row', 'A', FALSE),
  ('single-arm-cable-row', 'A', FALSE),
  ('smith-machine-row', 'B', FALSE),
  ('band-lateral-raise', 'B', TRUE),
  ('cable-external-rotation', 'B', FALSE),
  ('cable-front-raise', 'B', FALSE),
  ('handstand-push-up', 'S', TRUE),
  ('landmine-press', 'B', FALSE),
  ('machine-lateral-raise', 'A', FALSE),
  ('pike-push-up', 'A', TRUE),
  ('push-press', 'A', FALSE),
  ('band-curl', 'B', TRUE),
  ('barbell-21s', 'B', FALSE),
  ('drag-curl', 'B', FALSE),
  ('ez-bar-curl', 'A', FALSE),
  ('machine-curl', 'A', FALSE),
  ('reverse-curl', 'B', FALSE),
  ('rope-hammer-curl', 'B', FALSE),
  ('spider-curl', 'A', FALSE),
  ('band-overhead-triceps-extension', 'B', TRUE),
  ('band-pushdown', 'B', TRUE),
  ('cable-overhead-extension', 'A', FALSE),
  ('chair-dip', 'B', TRUE),
  ('jm-press', 'A', FALSE),
  ('machine-triceps-extension', 'A', FALSE),
  ('reverse-grip-pushdown', 'B', FALSE),
  ('single-arm-pushdown', 'B', FALSE),
  ('tate-press', 'B', TRUE),
  ('triceps-kickback', 'B', TRUE),
  ('barbell-wrist-curl', 'B', FALSE),
  ('cable-reverse-curl', 'B', FALSE),
  ('plate-pinch', 'B', FALSE),
  ('lateral-lunge', 'A', TRUE),
  ('pistol-squat', 'S', TRUE),
  ('reverse-lunge', 'A', TRUE),
  ('single-leg-press', 'A', FALSE),
  ('smith-machine-squat', 'B', FALSE),
  ('step-up-on-chair', 'B', TRUE),
  ('wall-sit', 'B', TRUE),
  ('glute-ham-raise', 'S', FALSE),
  ('good-morning', 'A', FALSE),
  ('nordic-curl', 'S', TRUE),
  ('seated-leg-curl', 'A', FALSE),
  ('band-deadlift', 'B', TRUE),
  ('band-glute-kickback', 'B', TRUE),
  ('banded-hip-abduction', 'B', TRUE),
  ('cable-kickback', 'B', FALSE),
  ('cable-pull-through', 'A', FALSE),
  ('crab-walk', 'B', TRUE),
  ('curtsy-lunge', 'B', TRUE),
  ('hip-abduction-machine', 'A', FALSE),
  ('side-lying-leg-raise', 'B', TRUE),
  ('sumo-deadlift', 'S', FALSE),
  ('bodyweight-calf-raise', 'B', TRUE),
  ('calf-raise-on-step', 'A', TRUE),
  ('dumbbell-calf-raise', 'A', TRUE),
  ('jumping-jack', 'B', TRUE),
  ('band-pallof-press', 'A', TRUE),
  ('bicycle-crunch', 'A', TRUE),
  ('bird-dog', 'A', TRUE),
  ('cable-woodchop', 'A', FALSE),
  ('crunch', 'B', TRUE),
  ('dead-bug', 'A', TRUE),
  ('farmer-carry', 'S', TRUE),
  ('flutter-kicks', 'B', TRUE),
  ('hanging-knee-raise', 'A', TRUE),
  ('hollow-hold', 'A', TRUE),
  ('inchworm', 'B', TRUE),
  ('lying-leg-raise', 'B', TRUE),
  ('pallof-press', 'A', FALSE),
  ('plank-shoulder-tap', 'A', TRUE),
  ('reverse-crunch', 'B', TRUE),
  ('v-up', 'A', TRUE),
  ('burpee', 'B', TRUE),
  ('elliptical', 'B', FALSE),
  ('high-knees', 'B', TRUE),
  ('incline-treadmill-walk', 'B', FALSE),
  ('sprint-intervals', 'B', TRUE),
  ('stair-climber', 'B', FALSE),
  ('butterfly-stretch', 'B', TRUE),
  ('calf-wall-stretch', 'B', TRUE),
  ('cat-cow', 'B', TRUE),
  ('childs-pose', 'B', TRUE),
  ('cobra-stretch', 'B', TRUE),
  ('shoulder-cross-body-stretch', 'B', TRUE),
  ('chest-doorway-stretch', 'B', TRUE),
  ('downward-dog', 'B', TRUE),
  ('hip-flexor-stretch', 'B', TRUE),
  ('triceps-overhead-stretch', 'B', TRUE),
  ('pigeon-pose', 'B', TRUE),
  ('seated-spinal-twist', 'B', TRUE),
  ('standing-hamstring-stretch', 'B', TRUE),
  ('lat-side-stretch', 'B', TRUE),
  ('quad-stretch', 'B', TRUE)
) AS v(slug, tier, home_friendly)
JOIN exercises e ON e.slug = v.slug
WHERE r.exercise_id = e.id;

-- Clear the review flags for exactly the rows just answered.
UPDATE exercises SET needs_tier_review = FALSE, needs_home_review = FALSE
WHERE slug IN (
  'archer-push-up',
  'decline-push-up',
  'dumbbell-pullover',
  'hindu-push-up',
  'incline-machine-press',
  'kettlebell-floor-press',
  'svend-press',
  'wide-push-up',
  'dumbbell-shrug',
  'inverted-row',
  'kettlebell-swing',
  'landmine-row',
  'neutral-grip-pull-up',
  'pendlay-row',
  'prone-y-raise',
  'rack-pull',
  'reverse-grip-lat-pulldown',
  'seal-row',
  'single-arm-cable-row',
  'smith-machine-row',
  'band-lateral-raise',
  'cable-external-rotation',
  'cable-front-raise',
  'handstand-push-up',
  'landmine-press',
  'machine-lateral-raise',
  'pike-push-up',
  'push-press',
  'band-curl',
  'barbell-21s',
  'drag-curl',
  'ez-bar-curl',
  'machine-curl',
  'reverse-curl',
  'rope-hammer-curl',
  'spider-curl',
  'band-overhead-triceps-extension',
  'band-pushdown',
  'cable-overhead-extension',
  'chair-dip',
  'jm-press',
  'machine-triceps-extension',
  'reverse-grip-pushdown',
  'single-arm-pushdown',
  'tate-press',
  'triceps-kickback',
  'barbell-wrist-curl',
  'cable-reverse-curl',
  'plate-pinch',
  'lateral-lunge',
  'pistol-squat',
  'reverse-lunge',
  'single-leg-press',
  'smith-machine-squat',
  'step-up-on-chair',
  'wall-sit',
  'glute-ham-raise',
  'good-morning',
  'nordic-curl',
  'seated-leg-curl',
  'band-deadlift',
  'band-glute-kickback',
  'banded-hip-abduction',
  'cable-kickback',
  'cable-pull-through',
  'crab-walk',
  'curtsy-lunge',
  'hip-abduction-machine',
  'side-lying-leg-raise',
  'sumo-deadlift',
  'bodyweight-calf-raise',
  'calf-raise-on-step',
  'dumbbell-calf-raise',
  'jumping-jack',
  'band-pallof-press',
  'bicycle-crunch',
  'bird-dog',
  'cable-woodchop',
  'crunch',
  'dead-bug',
  'farmer-carry',
  'flutter-kicks',
  'hanging-knee-raise',
  'hollow-hold',
  'inchworm',
  'lying-leg-raise',
  'pallof-press',
  'plank-shoulder-tap',
  'reverse-crunch',
  'v-up',
  'burpee',
  'elliptical',
  'high-knees',
  'incline-treadmill-walk',
  'sprint-intervals',
  'stair-climber',
  'butterfly-stretch',
  'calf-wall-stretch',
  'cat-cow',
  'childs-pose',
  'cobra-stretch',
  'shoulder-cross-body-stretch',
  'chest-doorway-stretch',
  'downward-dog',
  'hip-flexor-stretch',
  'triceps-overhead-stretch',
  'pigeon-pose',
  'seated-spinal-twist',
  'standing-hamstring-stretch',
  'lat-side-stretch',
  'quad-stretch'
);

COMMIT;

-- ROLLBACK: pre-commit run ROLLBACK; instead of COMMIT;
-- Post-commit: re-run 019 sections 4 (ratings) to restore defaults,
-- then UPDATE exercises SET needs_tier_review=TRUE, needs_home_review=TRUE
-- for the same 111 slugs listed above.