-- 021_exercise_safety_metadata.sql
-- Populates contraindicated_for and substitution_group for all 213 exercises.
-- contraindicated_for = questionnaire_rules.injury_based_exclusions (name-matched)
-- extended by movement pattern; every pattern-derived row is flagged
-- needs_injury_review = TRUE for manual sign-off.
-- Data only — no app code depends on this migration.
-- Paste into Supabase Dashboard -> SQL Editor -> Run.

BEGIN;

ALTER TABLE exercises
  ADD COLUMN IF NOT EXISTS needs_injury_review BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE exercises e
SET contraindicated_for   = v.contra,
    substitution_group    = v.grp,
    needs_injury_review   = v.review
FROM (VALUES
  ('assisted-pull-up', '{}'::TEXT[], 'back_vertical_pull', FALSE),
  ('back-extension', ARRAY['Lower back']::TEXT[], 'back_spinal_extension', TRUE),
  ('barbell-shrug', ARRAY['Lower back','Neck']::TEXT[], 'back_shrug', FALSE),
  ('bent-over-barbell-row', ARRAY['Lower back']::TEXT[], 'back_horizontal_row', FALSE),
  ('chest-supported-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('close-grip-lat-pulldown', ARRAY['Wrist / elbow']::TEXT[], 'back_vertical_pull', TRUE),
  ('deadlift', ARRAY['Lower back']::TEXT[], 'back_hip_hinge', FALSE),
  ('dumbbell-row', ARRAY['Lower back']::TEXT[], 'back_horizontal_row', TRUE),
  ('dumbbell-shrug', ARRAY['Neck']::TEXT[], 'back_shrug', TRUE),
  ('inverted-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('kettlebell-swing', ARRAY['Lower back']::TEXT[], 'back_kb_swing', TRUE),
  ('landmine-row', ARRAY['Lower back']::TEXT[], 'back_horizontal_row', TRUE),
  ('lat-pulldown', '{}'::TEXT[], 'back_vertical_pull', FALSE),
  ('machine-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('neutral-grip-pull-up', '{}'::TEXT[], 'back_vertical_pull', FALSE),
  ('pendlay-row', ARRAY['Lower back']::TEXT[], 'back_horizontal_row', TRUE),
  ('pull-up', '{}'::TEXT[], 'back_vertical_pull', FALSE),
  ('rack-pull', ARRAY['Lower back']::TEXT[], 'back_hip_hinge', TRUE),
  ('reverse-grip-lat-pulldown', ARRAY['Wrist / elbow']::TEXT[], 'back_vertical_pull', TRUE),
  ('seal-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('seated-cable-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('single-arm-cable-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('smith-machine-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('straight-arm-pulldown', '{}'::TEXT[], 'back_vertical_pull', FALSE),
  ('t-bar-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('band-chest-press', '{}'::TEXT[], 'chest_horizontal_press', FALSE),
  ('band-deadlift', ARRAY['Lower back']::TEXT[], 'glutes_hip_hinge', TRUE),
  ('band-face-pull', '{}'::TEXT[], 'shoulders_rear_delt', FALSE),
  ('band-glute-kickback', '{}'::TEXT[], 'glutes_glute_iso', FALSE),
  ('band-overhead-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('band-overhead-triceps-extension', '{}'::TEXT[], 'triceps_triceps_extension', FALSE),
  ('band-pallof-press', '{}'::TEXT[], 'core_anti_rotation', FALSE),
  ('band-pull-apart', '{}'::TEXT[], 'shoulders_rear_delt', FALSE),
  ('band-row', '{}'::TEXT[], 'back_horizontal_row', FALSE),
  ('band-squat', '{}'::TEXT[], 'quads_squat', FALSE),
  ('band-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('barbell-21s', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('barbell-curl', ARRAY['Wrist / elbow']::TEXT[], 'biceps_biceps_curl', FALSE),
  ('cable-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('chin-up', '{}'::TEXT[], 'biceps_chin_up', FALSE),
  ('concentration-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('drag-curl', ARRAY['Wrist / elbow']::TEXT[], 'biceps_biceps_curl', TRUE),
  ('dumbbell-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('ez-bar-curl', ARRAY['Wrist / elbow']::TEXT[], 'biceps_biceps_curl', TRUE),
  ('hammer-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('incline-dumbbell-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('machine-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('preacher-curl', ARRAY['Wrist / elbow']::TEXT[], 'biceps_biceps_curl', TRUE),
  ('reverse-curl', ARRAY['Wrist / elbow']::TEXT[], 'biceps_biceps_curl', TRUE),
  ('rope-hammer-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('spider-curl', '{}'::TEXT[], 'biceps_biceps_curl', FALSE),
  ('burpee', '{}'::TEXT[], NULL, FALSE),
  ('elliptical', '{}'::TEXT[], NULL, FALSE),
  ('high-knees', '{}'::TEXT[], NULL, FALSE),
  ('incline-treadmill-walk', '{}'::TEXT[], NULL, FALSE),
  ('jump-rope', ARRAY['Knee']::TEXT[], NULL, TRUE),
  ('rowing-machine', '{}'::TEXT[], NULL, FALSE),
  ('sprint-intervals', '{}'::TEXT[], NULL, FALSE),
  ('stair-climber', '{}'::TEXT[], NULL, FALSE),
  ('stationary-bike', '{}'::TEXT[], NULL, FALSE),
  ('treadmill-run', '{}'::TEXT[], NULL, FALSE),
  ('barbell-bench-press', ARRAY['Shoulder']::TEXT[], 'chest_horizontal_press', TRUE),
  ('cable-crossover', '{}'::TEXT[], 'chest_chest_fly', FALSE),
  ('chest-dip', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'chest_chest_dip', TRUE),
  ('decline-barbell-press', '{}'::TEXT[], 'chest_decline_press', FALSE),
  ('decline-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_decline_press', TRUE),
  ('dumbbell-bench-press', ARRAY['Shoulder']::TEXT[], 'chest_horizontal_press', TRUE),
  ('dumbbell-fly', '{}'::TEXT[], 'chest_chest_fly', FALSE),
  ('dumbbell-pullover', '{}'::TEXT[], 'chest_pullover', FALSE),
  ('incline-barbell-press', '{}'::TEXT[], 'chest_incline_press', FALSE),
  ('incline-cable-fly', '{}'::TEXT[], 'chest_incline_press', FALSE),
  ('incline-dumbbell-press', '{}'::TEXT[], 'chest_incline_press', FALSE),
  ('incline-machine-press', '{}'::TEXT[], 'chest_incline_press', FALSE),
  ('kettlebell-floor-press', '{}'::TEXT[], 'chest_horizontal_press', FALSE),
  ('machine-chest-press', '{}'::TEXT[], 'chest_horizontal_press', FALSE),
  ('pec-deck', '{}'::TEXT[], 'chest_chest_fly', FALSE),
  ('push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', FALSE),
  ('svend-press', '{}'::TEXT[], 'chest_chest_fly', FALSE),
  ('wide-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', TRUE),
  ('ab-wheel-rollout', ARRAY['Wrist / elbow']::TEXT[], 'core_rollout', TRUE),
  ('bicycle-crunch', '{}'::TEXT[], 'core_crunch', FALSE),
  ('bird-dog', '{}'::TEXT[], 'core_plank', FALSE),
  ('cable-crunch', '{}'::TEXT[], 'core_crunch', FALSE),
  ('cable-woodchop', '{}'::TEXT[], 'core_anti_rotation', FALSE),
  ('crunch', '{}'::TEXT[], 'core_crunch', FALSE),
  ('dead-bug', '{}'::TEXT[], 'core_plank', FALSE),
  ('farmer-carry', '{}'::TEXT[], 'core_carry', FALSE),
  ('hanging-knee-raise', '{}'::TEXT[], 'core_crunch', FALSE),
  ('hanging-leg-raise', '{}'::TEXT[], 'core_crunch', FALSE),
  ('hollow-hold', '{}'::TEXT[], 'core_plank', FALSE),
  ('lying-leg-raise', '{}'::TEXT[], 'core_crunch', FALSE),
  ('mountain-climber', '{}'::TEXT[], 'core_cardio_core', FALSE),
  ('pallof-press', '{}'::TEXT[], 'core_anti_rotation', FALSE),
  ('plank', '{}'::TEXT[], 'core_plank', FALSE),
  ('reverse-crunch', '{}'::TEXT[], 'core_crunch', FALSE),
  ('russian-twist', '{}'::TEXT[], 'core_anti_rotation', FALSE),
  ('side-plank', '{}'::TEXT[], 'core_plank', FALSE),
  ('sit-up', '{}'::TEXT[], 'core_crunch', FALSE),
  ('v-up', '{}'::TEXT[], 'core_crunch', FALSE),
  ('barbell-wrist-curl', ARRAY['Wrist / elbow']::TEXT[], 'forearms_wrist_curl', TRUE),
  ('cable-reverse-curl', ARRAY['Wrist / elbow']::TEXT[], 'forearms_reverse_curl', TRUE),
  ('dead-hang', '{}'::TEXT[], 'forearms_grip', FALSE),
  ('plate-pinch', ARRAY['Wrist / elbow']::TEXT[], 'forearms_grip', TRUE),
  ('reverse-wrist-curl', '{}'::TEXT[], 'forearms_wrist_curl', FALSE),
  ('wrist-curl', '{}'::TEXT[], 'forearms_wrist_curl', FALSE),
  ('archer-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', TRUE),
  ('bear-crawl', ARRAY['Wrist / elbow']::TEXT[], 'core_plank', TRUE),
  ('calf-raise-on-step', '{}'::TEXT[], 'calves_calf_raise', FALSE),
  ('chair-dip', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'triceps_triceps_dip', TRUE),
  ('crab-walk', '{}'::TEXT[], 'glutes_glute_iso', FALSE),
  ('curtsy-lunge', ARRAY['Knee']::TEXT[], 'glutes_lunge', TRUE),
  ('donkey-kick', '{}'::TEXT[], 'glutes_glute_iso', FALSE),
  ('fire-hydrant', '{}'::TEXT[], 'glutes_abduction', FALSE),
  ('flutter-kicks', '{}'::TEXT[], 'core_crunch', FALSE),
  ('hindu-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', TRUE),
  ('inchworm', '{}'::TEXT[], 'core_plank', FALSE),
  ('incline-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_incline_press', TRUE),
  ('jump-squat', ARRAY['Knee']::TEXT[], 'quads_squat', FALSE),
  ('jumping-jack', ARRAY['Knee']::TEXT[], 'calves_plyo', TRUE),
  ('knee-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', TRUE),
  ('lateral-lunge', ARRAY['Knee']::TEXT[], 'quads_lunge', TRUE),
  ('pistol-squat', ARRAY['Knee']::TEXT[], 'quads_squat', TRUE),
  ('plank-shoulder-tap', ARRAY['Wrist / elbow']::TEXT[], 'core_plank', TRUE),
  ('prone-y-raise', '{}'::TEXT[], 'back_spinal_extension', FALSE),
  ('side-lying-leg-raise', '{}'::TEXT[], 'glutes_abduction', FALSE),
  ('single-leg-glute-bridge', '{}'::TEXT[], 'glutes_hip_thrust', FALSE),
  ('standing-knee-to-elbow', '{}'::TEXT[], 'core_crunch', FALSE),
  ('step-up-on-chair', ARRAY['Knee']::TEXT[], 'quads_lunge', TRUE),
  ('superman', ARRAY['Lower back']::TEXT[], 'back_spinal_extension', TRUE),
  ('wall-push-up', ARRAY['Wrist / elbow']::TEXT[], 'chest_horizontal_press', TRUE),
  ('back-squat', ARRAY['Knee','Lower back']::TEXT[], 'quads_squat', FALSE),
  ('banded-hip-abduction', '{}'::TEXT[], 'glutes_abduction', FALSE),
  ('bodyweight-calf-raise', '{}'::TEXT[], 'calves_calf_raise', FALSE),
  ('bodyweight-squat', '{}'::TEXT[], 'quads_squat', FALSE),
  ('bulgarian-split-squat', ARRAY['Knee']::TEXT[], 'quads_lunge', FALSE),
  ('cable-kickback', '{}'::TEXT[], 'glutes_glute_iso', FALSE),
  ('cable-pull-through', ARRAY['Lower back']::TEXT[], 'glutes_hip_hinge', TRUE),
  ('dumbbell-calf-raise', '{}'::TEXT[], 'calves_calf_raise', FALSE),
  ('dumbbell-rdl', ARRAY['Lower back']::TEXT[], 'hamstrings_hip_hinge', FALSE),
  ('front-squat', ARRAY['Knee','Lower back','Wrist / elbow']::TEXT[], 'quads_squat', FALSE),
  ('glute-bridge', '{}'::TEXT[], 'glutes_hip_thrust', FALSE),
  ('glute-ham-raise', '{}'::TEXT[], 'hamstrings_leg_curl', FALSE),
  ('goblet-squat', '{}'::TEXT[], 'quads_squat', FALSE),
  ('good-morning', ARRAY['Lower back']::TEXT[], 'hamstrings_good_morning', FALSE),
  ('hack-squat', ARRAY['Knee']::TEXT[], 'quads_leg_press', TRUE),
  ('hip-abduction-machine', '{}'::TEXT[], 'glutes_abduction', FALSE),
  ('hip-thrust', '{}'::TEXT[], 'glutes_hip_thrust', FALSE),
  ('leg-extension', ARRAY['Knee']::TEXT[], 'quads_leg_extension', FALSE),
  ('leg-press', '{}'::TEXT[], 'quads_leg_press', FALSE),
  ('lying-leg-curl', '{}'::TEXT[], 'hamstrings_leg_curl', FALSE),
  ('nordic-curl', '{}'::TEXT[], 'hamstrings_leg_curl', FALSE),
  ('reverse-lunge', ARRAY['Knee']::TEXT[], 'quads_lunge', TRUE),
  ('romanian-deadlift', ARRAY['Lower back']::TEXT[], 'hamstrings_hip_hinge', FALSE),
  ('seated-calf-raise', '{}'::TEXT[], 'calves_calf_raise', FALSE),
  ('seated-leg-curl', '{}'::TEXT[], 'hamstrings_leg_curl', FALSE),
  ('single-leg-press', '{}'::TEXT[], 'quads_leg_press', FALSE),
  ('smith-machine-squat', ARRAY['Knee']::TEXT[], 'quads_squat', TRUE),
  ('standing-calf-raise', '{}'::TEXT[], 'calves_calf_raise', FALSE),
  ('step-up', ARRAY['Knee']::TEXT[], 'quads_lunge', FALSE),
  ('sumo-deadlift', ARRAY['Lower back']::TEXT[], 'glutes_hip_hinge', TRUE),
  ('walking-lunge', ARRAY['Knee']::TEXT[], 'quads_lunge', FALSE),
  ('wall-sit', '{}'::TEXT[], 'quads_wall_sit', FALSE),
  ('arnold-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', FALSE),
  ('band-lateral-raise', '{}'::TEXT[], 'shoulders_lateral_raise', FALSE),
  ('cable-external-rotation', '{}'::TEXT[], 'shoulders_ext_rotation', FALSE),
  ('cable-front-raise', '{}'::TEXT[], 'shoulders_front_raise', FALSE),
  ('cable-lateral-raise', '{}'::TEXT[], 'shoulders_lateral_raise', FALSE),
  ('dumbbell-rear-delt-fly', '{}'::TEXT[], 'shoulders_rear_delt', FALSE),
  ('dumbbell-shoulder-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', FALSE),
  ('face-pull', '{}'::TEXT[], 'shoulders_rear_delt', FALSE),
  ('front-raise', '{}'::TEXT[], 'shoulders_front_raise', FALSE),
  ('handstand-push-up', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('landmine-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('lateral-raise', '{}'::TEXT[], 'shoulders_lateral_raise', FALSE),
  ('machine-lateral-raise', '{}'::TEXT[], 'shoulders_lateral_raise', FALSE),
  ('machine-shoulder-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('overhead-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', FALSE),
  ('pike-push-up', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('push-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', TRUE),
  ('reverse-pec-deck', '{}'::TEXT[], 'shoulders_rear_delt', FALSE),
  ('seated-barbell-press', ARRAY['Shoulder']::TEXT[], 'shoulders_overhead_press', FALSE),
  ('upright-row', ARRAY['Lower back','Neck','Shoulder']::TEXT[], 'shoulders_upright_row', TRUE),
  ('butterfly-stretch', '{}'::TEXT[], NULL, FALSE),
  ('calf-wall-stretch', '{}'::TEXT[], NULL, FALSE),
  ('cat-cow', '{}'::TEXT[], NULL, FALSE),
  ('chest-doorway-stretch', '{}'::TEXT[], NULL, FALSE),
  ('childs-pose', '{}'::TEXT[], NULL, FALSE),
  ('cobra-stretch', '{}'::TEXT[], NULL, FALSE),
  ('downward-dog', '{}'::TEXT[], NULL, FALSE),
  ('hip-flexor-stretch', '{}'::TEXT[], NULL, FALSE),
  ('lat-side-stretch', '{}'::TEXT[], NULL, FALSE),
  ('pigeon-pose', '{}'::TEXT[], NULL, FALSE),
  ('quad-stretch', '{}'::TEXT[], NULL, FALSE),
  ('seated-spinal-twist', '{}'::TEXT[], NULL, FALSE),
  ('shoulder-cross-body-stretch', '{}'::TEXT[], NULL, FALSE),
  ('standing-hamstring-stretch', '{}'::TEXT[], NULL, FALSE),
  ('triceps-overhead-stretch', '{}'::TEXT[], NULL, FALSE),
  ('band-pushdown', '{}'::TEXT[], 'triceps_pushdown', FALSE),
  ('bench-dip', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'triceps_triceps_dip', TRUE),
  ('cable-overhead-extension', '{}'::TEXT[], 'triceps_triceps_extension', FALSE),
  ('close-grip-bench-press', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'triceps_close_grip_press', TRUE),
  ('diamond-push-up', ARRAY['Wrist / elbow']::TEXT[], 'triceps_close_grip_press', FALSE),
  ('jm-press', ARRAY['Wrist / elbow']::TEXT[], 'triceps_triceps_extension', TRUE),
  ('machine-triceps-extension', '{}'::TEXT[], 'triceps_triceps_extension', FALSE),
  ('overhead-triceps-extension', '{}'::TEXT[], 'triceps_triceps_extension', FALSE),
  ('parallel-bar-dip', ARRAY['Shoulder','Wrist / elbow']::TEXT[], 'triceps_triceps_dip', TRUE),
  ('reverse-grip-pushdown', ARRAY['Wrist / elbow']::TEXT[], 'triceps_pushdown', TRUE),
  ('rope-pushdown', '{}'::TEXT[], 'triceps_pushdown', FALSE),
  ('single-arm-pushdown', '{}'::TEXT[], 'triceps_pushdown', FALSE),
  ('skull-crusher', ARRAY['Wrist / elbow']::TEXT[], 'triceps_triceps_extension', FALSE),
  ('tate-press', ARRAY['Wrist / elbow']::TEXT[], 'triceps_triceps_extension', TRUE),
  ('triceps-kickback', '{}'::TEXT[], 'triceps_triceps_extension', FALSE),
  ('triceps-pushdown', '{}'::TEXT[], 'triceps_pushdown', FALSE)
) AS v(slug, contra, grp, review)
WHERE e.slug = v.slug;

COMMIT;

-- ROLLBACK: pre-commit run ROLLBACK; instead of COMMIT;
-- Post-commit:
--   UPDATE exercises SET contraindicated_for = NULL, substitution_group = NULL,
--                       needs_injury_review = FALSE;
--   ALTER TABLE exercises DROP COLUMN IF EXISTS needs_injury_review;