-- 024_exercise_roles.sql
-- Adds the role / sub_target / true_max_effort tags the training-logic spec
-- drives every ordering and set/rep decision from.
--
-- Derived from the EXISTING catalog only — substitution_group + equipment +
-- exercise_ratings.tier. No rows inserted, no names changed, nothing
-- reconciled against an external JSON.
-- Paste into Supabase Dashboard -> SQL Editor -> Run.

BEGIN;

ALTER TABLE exercises
  ADD COLUMN IF NOT EXISTS role TEXT
    CHECK (role IS NULL OR role IN ('opener_heavy','opener_compound','mid_compound',
      'mid_compound_machine','mid_isolation','opener_isolation','finisher_compound','finisher_isolation')),
  ADD COLUMN IF NOT EXISTS sub_target TEXT,
  ADD COLUMN IF NOT EXISTS true_max_effort BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS needs_role_review BOOLEAN NOT NULL DEFAULT FALSE;

-- NB: the role/type guard is added AFTER the UPDATE below. Adding it here
-- would fail instantly — every strength row still has role IS NULL at this
-- point, so the constraint is violated before the data exists to satisfy it.

UPDATE exercises e
SET role = v.role, sub_target = v.sub_target, true_max_effort = v.tme,
    needs_role_review = TRUE
FROM (VALUES
  ('assisted-pull-up', 'mid_compound_machine', 'vertical_pull', FALSE),
  ('back-extension', 'mid_isolation', 'spinal_extension', FALSE),
  ('barbell-shrug', 'finisher_isolation', 'shrug', FALSE),
  ('bent-over-barbell-row', 'opener_heavy', 'horizontal_row', TRUE),
  ('chest-supported-row', 'opener_compound', 'horizontal_row', FALSE),
  ('close-grip-lat-pulldown', 'mid_compound', 'vertical_pull', FALSE),
  ('deadlift', 'opener_heavy', 'hip_hinge', TRUE),
  ('band-pull-apart', 'opener_isolation', 'rear_delt_region', FALSE),
  ('band-row', 'finisher_compound', 'horizontal_row', FALSE),
  ('band-squat', 'finisher_compound', 'squat', FALSE),
  ('band-curl', 'finisher_isolation', 'biceps_curl', FALSE),
  ('dumbbell-row', 'opener_compound', 'horizontal_row', FALSE),
  ('dumbbell-shrug', 'mid_isolation', 'shrug', FALSE),
  ('inverted-row', 'opener_compound', 'horizontal_row', FALSE),
  ('kettlebell-swing', 'mid_compound', 'kb_swing', FALSE),
  ('landmine-row', 'finisher_compound', 'horizontal_row', FALSE),
  ('lat-pulldown', 'opener_compound', 'vertical_pull', FALSE),
  ('machine-row', 'mid_compound_machine', 'horizontal_row', FALSE),
  ('neutral-grip-pull-up', 'opener_compound', 'vertical_pull', FALSE),
  ('pendlay-row', 'opener_heavy', 'horizontal_row', TRUE),
  ('pull-up', 'opener_compound', 'vertical_pull', FALSE),
  ('rack-pull', 'finisher_compound', 'hip_hinge', FALSE),
  ('barbell-21s', 'finisher_isolation', 'biceps_curl', FALSE),
  ('barbell-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('reverse-grip-lat-pulldown', 'mid_compound', 'vertical_pull', FALSE),
  ('seal-row', 'mid_compound', 'horizontal_row', FALSE),
  ('seated-cable-row', 'opener_compound', 'horizontal_row', FALSE),
  ('single-arm-cable-row', 'mid_compound', 'horizontal_row', FALSE),
  ('smith-machine-row', 'mid_compound_machine', 'horizontal_row', FALSE),
  ('straight-arm-pulldown', 'mid_compound', 'vertical_pull', FALSE),
  ('t-bar-row', 'opener_heavy', 'horizontal_row', TRUE),
  ('band-chest-press', 'finisher_compound', 'horizontal_press', FALSE),
  ('band-deadlift', 'finisher_compound', 'hip_hinge', FALSE),
  ('band-face-pull', 'opener_isolation', 'rear_delt_region', FALSE),
  ('band-glute-kickback', 'finisher_isolation', 'glute_iso', FALSE),
  ('band-overhead-press', 'finisher_compound', 'press_region', FALSE),
  ('band-overhead-triceps-extension', 'finisher_isolation', 'triceps_extension', FALSE),
  ('band-pallof-press', 'mid_isolation', 'anti_rotation', FALSE),
  ('cable-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('chin-up', 'opener_compound', 'chin_up', FALSE),
  ('concentration-curl', 'finisher_isolation', 'biceps_curl', FALSE),
  ('drag-curl', 'finisher_isolation', 'biceps_curl', FALSE),
  ('dumbbell-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('ez-bar-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('hammer-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('incline-dumbbell-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('machine-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('preacher-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('reverse-curl', 'finisher_isolation', 'biceps_curl', FALSE),
  ('rope-hammer-curl', 'finisher_isolation', 'biceps_curl', FALSE),
  ('spider-curl', 'mid_isolation', 'biceps_curl', FALSE),
  ('burpee', NULL, NULL, FALSE),
  ('elliptical', NULL, NULL, FALSE),
  ('incline-treadmill-walk', NULL, NULL, FALSE),
  ('jump-rope', NULL, NULL, FALSE),
  ('rowing-machine', NULL, NULL, FALSE),
  ('sprint-intervals', NULL, NULL, FALSE),
  ('stair-climber', NULL, NULL, FALSE),
  ('stationary-bike', NULL, NULL, FALSE),
  ('treadmill-run', NULL, NULL, FALSE),
  ('barbell-bench-press', 'opener_heavy', 'horizontal_press', TRUE),
  ('cable-crossover', 'mid_isolation', 'chest_fly', FALSE),
  ('chest-dip', 'opener_compound', 'chest_dip', FALSE),
  ('decline-barbell-press', 'mid_compound', 'decline_press', FALSE),
  ('decline-push-up', 'mid_compound', 'decline_press', FALSE),
  ('dumbbell-bench-press', 'opener_compound', 'horizontal_press', FALSE),
  ('dumbbell-fly', 'mid_isolation', 'chest_fly', FALSE),
  ('dumbbell-pullover', 'finisher_isolation', 'pullover', FALSE),
  ('incline-barbell-press', 'opener_heavy', 'incline_press', TRUE),
  ('incline-cable-fly', 'mid_compound', 'incline_press', FALSE),
  ('incline-dumbbell-press', 'opener_compound', 'incline_press', FALSE),
  ('incline-machine-press', 'mid_compound_machine', 'incline_press', FALSE),
  ('kettlebell-floor-press', 'finisher_compound', 'horizontal_press', FALSE),
  ('hollow-hold', 'mid_isolation', 'plank', FALSE),
  ('lying-leg-raise', 'finisher_isolation', 'crunch', FALSE),
  ('mountain-climber', 'finisher_isolation', 'cardio_core', FALSE),
  ('pallof-press', 'mid_isolation', 'anti_rotation', FALSE),
  ('plank', 'mid_isolation', 'plank', FALSE),
  ('reverse-crunch', 'finisher_isolation', 'crunch', FALSE),
  ('russian-twist', 'finisher_isolation', 'anti_rotation', FALSE),
  ('side-plank', 'mid_isolation', 'plank', FALSE),
  ('sit-up', 'finisher_isolation', 'crunch', FALSE),
  ('v-up', 'mid_isolation', 'crunch', FALSE),
  ('wrist-curl', 'finisher_isolation', 'wrist_curl', FALSE),
  ('archer-push-up', 'mid_compound', 'horizontal_press', FALSE),
  ('calf-raise-on-step', 'mid_isolation', 'calf_raise', FALSE),
  ('chair-dip', 'finisher_compound', 'triceps_dip', FALSE),
  ('crab-walk', 'finisher_isolation', 'glute_iso', FALSE),
  ('machine-chest-press', 'mid_compound_machine', 'horizontal_press', FALSE),
  ('pec-deck', 'mid_isolation', 'chest_fly', FALSE),
  ('push-up', 'opener_compound', 'horizontal_press', FALSE),
  ('svend-press', 'finisher_isolation', 'chest_fly', FALSE),
  ('wide-push-up', 'mid_compound', 'horizontal_press', FALSE),
  ('ab-wheel-rollout', 'mid_isolation', 'rollout', FALSE),
  ('bicycle-crunch', 'mid_isolation', 'crunch', FALSE),
  ('bird-dog', 'mid_isolation', 'plank', FALSE),
  ('cable-crunch', 'mid_isolation', 'crunch', FALSE),
  ('cable-woodchop', 'mid_isolation', 'anti_rotation', FALSE),
  ('crunch', 'finisher_isolation', 'crunch', FALSE),
  ('dead-bug', 'mid_isolation', 'plank', FALSE),
  ('farmer-carry', 'mid_isolation', 'carry', FALSE),
  ('hanging-knee-raise', 'mid_isolation', 'crunch', FALSE),
  ('hanging-leg-raise', 'mid_isolation', 'crunch', FALSE),
  ('bear-crawl', 'finisher_isolation', 'plank', FALSE),
  ('curtsy-lunge', 'finisher_compound', 'lunge', FALSE),
  ('donkey-kick', 'finisher_isolation', 'glute_iso', FALSE),
  ('fire-hydrant', 'finisher_isolation', 'abduction', FALSE),
  ('flutter-kicks', 'finisher_isolation', 'crunch', FALSE),
  ('hindu-push-up', 'finisher_compound', 'horizontal_press', FALSE),
  ('inchworm', 'finisher_isolation', 'plank', FALSE),
  ('incline-push-up', 'finisher_compound', 'incline_press', FALSE),
  ('jump-squat', 'mid_compound', 'squat', FALSE),
  ('jumping-jack', 'finisher_isolation', 'plyo', FALSE),
  ('knee-push-up', 'finisher_compound', 'horizontal_press', FALSE),
  ('lateral-lunge', 'mid_compound', 'lunge', FALSE),
  ('pistol-squat', 'opener_compound', 'squat', FALSE),
  ('plank-shoulder-tap', 'mid_isolation', 'plank', FALSE),
  ('prone-y-raise', 'finisher_isolation', 'spinal_extension', FALSE),
  ('side-lying-leg-raise', 'finisher_isolation', 'abduction', FALSE),
  ('single-leg-glute-bridge', 'mid_compound', 'hip_thrust', FALSE),
  ('standing-knee-to-elbow', 'finisher_isolation', 'crunch', FALSE),
  ('step-up-on-chair', 'finisher_compound', 'lunge', FALSE),
  ('superman', 'finisher_isolation', 'spinal_extension', FALSE),
  ('wall-push-up', 'finisher_compound', 'horizontal_press', FALSE),
  ('barbell-wrist-curl', 'finisher_isolation', 'wrist_curl', FALSE),
  ('cable-reverse-curl', 'finisher_isolation', 'reverse_curl', FALSE),
  ('dead-hang', 'finisher_isolation', 'grip', FALSE),
  ('plate-pinch', 'finisher_isolation', 'grip', FALSE),
  ('reverse-wrist-curl', 'finisher_isolation', 'wrist_curl', FALSE),
  ('back-squat', 'opener_heavy', 'squat', TRUE),
  ('banded-hip-abduction', 'finisher_isolation', 'abduction', FALSE),
  ('bodyweight-calf-raise', 'finisher_isolation', 'calf_raise', FALSE),
  ('bodyweight-squat', 'mid_compound', 'squat', FALSE),
  ('bulgarian-split-squat', 'opener_compound', 'lunge', FALSE),
  ('cable-kickback', 'finisher_isolation', 'glute_iso', FALSE),
  ('cable-pull-through', 'mid_compound', 'hip_hinge', FALSE),
  ('dumbbell-calf-raise', 'mid_isolation', 'calf_raise', FALSE),
  ('dumbbell-rdl', 'opener_compound', 'hip_hinge', FALSE),
  ('front-squat', 'opener_heavy', 'squat', TRUE),
  ('glute-bridge', 'mid_compound', 'hip_thrust', FALSE),
  ('glute-ham-raise', 'mid_isolation', 'leg_curl', FALSE),
  ('goblet-squat', 'opener_compound', 'squat', FALSE),
  ('good-morning', 'mid_compound', 'good_morning', FALSE),
  ('hack-squat', 'mid_compound_machine', 'leg_press', FALSE),
  ('hip-abduction-machine', 'mid_isolation', 'abduction', FALSE),
  ('hip-thrust', 'opener_heavy', 'hip_thrust', TRUE),
  ('leg-extension', 'mid_isolation', 'leg_extension', FALSE),
  ('leg-press', 'mid_compound_machine', 'leg_press', FALSE),
  ('lying-leg-curl', 'mid_isolation', 'leg_curl', FALSE),
  ('nordic-curl', 'mid_isolation', 'leg_curl', FALSE),
  ('reverse-lunge', 'mid_compound', 'lunge', FALSE),
  ('romanian-deadlift', 'opener_heavy', 'hip_hinge', TRUE),
  ('seated-calf-raise', 'mid_isolation', 'calf_raise', FALSE),
  ('seated-leg-curl', 'mid_isolation', 'leg_curl', FALSE),
  ('single-leg-press', 'mid_compound_machine', 'leg_press', FALSE),
  ('smith-machine-squat', 'mid_compound_machine', 'squat', FALSE),
  ('standing-calf-raise', 'mid_isolation', 'calf_raise', FALSE),
  ('step-up', 'mid_compound', 'lunge', FALSE),
  ('sumo-deadlift', 'opener_heavy', 'hip_hinge', TRUE),
  ('walking-lunge', 'mid_compound', 'lunge', FALSE),
  ('wall-sit', 'finisher_isolation', 'wall_sit', FALSE),
  ('arnold-press', 'mid_compound', 'press_region', FALSE),
  ('band-lateral-raise', 'finisher_isolation', 'side_delt_region', FALSE),
  ('cable-external-rotation', 'opener_isolation', 'rotator_cuff_region', FALSE),
  ('cable-front-raise', 'finisher_isolation', 'front_delt_region', FALSE),
  ('cable-lateral-raise', 'mid_isolation', 'side_delt_region', FALSE),
  ('dumbbell-rear-delt-fly', 'opener_isolation', 'rear_delt_region', FALSE),
  ('dumbbell-shoulder-press', 'opener_compound', 'press_region', FALSE),
  ('face-pull', 'opener_isolation', 'rear_delt_region', FALSE),
  ('front-raise', 'finisher_isolation', 'front_delt_region', FALSE),
  ('machine-lateral-raise', 'mid_isolation', 'side_delt_region', FALSE),
  ('triceps-overhead-stretch', NULL, NULL, FALSE),
  ('band-pushdown', 'finisher_isolation', 'pushdown', FALSE),
  ('cable-overhead-extension', 'mid_isolation', 'triceps_extension', FALSE),
  ('jm-press', 'mid_isolation', 'triceps_extension', FALSE),
  ('machine-triceps-extension', 'mid_isolation', 'triceps_extension', FALSE),
  ('reverse-grip-pushdown', 'finisher_isolation', 'pushdown', FALSE),
  ('single-arm-pushdown', 'finisher_isolation', 'pushdown', FALSE),
  ('tate-press', 'finisher_isolation', 'triceps_extension', FALSE),
  ('triceps-kickback', 'finisher_isolation', 'triceps_extension', FALSE),
  ('triceps-pushdown', 'mid_isolation', 'pushdown', FALSE),
  ('handstand-push-up', 'opener_compound', 'press_region', FALSE),
  ('landmine-press', 'finisher_compound', 'press_region', FALSE),
  ('lateral-raise', 'mid_isolation', 'side_delt_region', FALSE),
  ('cat-cow', NULL, NULL, FALSE),
  ('machine-shoulder-press', 'mid_compound_machine', 'press_region', FALSE),
  ('overhead-press', 'opener_heavy', 'press_region', TRUE),
  ('reverse-pec-deck', 'opener_isolation', 'rear_delt_region', FALSE),
  ('seated-barbell-press', 'opener_heavy', 'press_region', TRUE),
  ('upright-row', 'finisher_compound', 'upright_row', FALSE),
  ('bench-dip', 'finisher_compound', 'triceps_dip', FALSE),
  ('close-grip-bench-press', 'opener_heavy', 'close_grip_press', TRUE),
  ('diamond-push-up', 'finisher_compound', 'close_grip_press', FALSE),
  ('overhead-triceps-extension', 'mid_isolation', 'triceps_extension', FALSE),
  ('parallel-bar-dip', 'opener_compound', 'triceps_dip', FALSE),
  ('rope-pushdown', 'mid_isolation', 'pushdown', FALSE),
  ('skull-crusher', 'mid_isolation', 'triceps_extension', FALSE),
  ('high-knees', NULL, NULL, FALSE),
  ('pike-push-up', 'mid_compound', 'press_region', FALSE),
  ('push-press', 'mid_compound', 'press_region', FALSE),
  ('butterfly-stretch', NULL, NULL, FALSE),
  ('calf-wall-stretch', NULL, NULL, FALSE),
  ('chest-doorway-stretch', NULL, NULL, FALSE),
  ('childs-pose', NULL, NULL, FALSE),
  ('cobra-stretch', NULL, NULL, FALSE),
  ('downward-dog', NULL, NULL, FALSE),
  ('hip-flexor-stretch', NULL, NULL, FALSE),
  ('lat-side-stretch', NULL, NULL, FALSE),
  ('pigeon-pose', NULL, NULL, FALSE),
  ('quad-stretch', NULL, NULL, FALSE),
  ('seated-spinal-twist', NULL, NULL, FALSE),
  ('shoulder-cross-body-stretch', NULL, NULL, FALSE),
  ('standing-hamstring-stretch', NULL, NULL, FALSE)
) AS v(slug, role, sub_target, tme)
WHERE e.slug = v.slug;

-- Now the data satisfies it: cardio/stretching rows never fill a muscle
-- slot, so they carry no role; every strength row must have one.
ALTER TABLE exercises DROP CONSTRAINT IF EXISTS exercises_role_by_type_check;
ALTER TABLE exercises ADD CONSTRAINT exercises_role_by_type_check CHECK (
  (exercise_type = 'strength' AND role IS NOT NULL)
  OR (exercise_type <> 'strength' AND role IS NULL)
);

COMMIT;

-- ROLLBACK: pre-commit run ROLLBACK; instead of COMMIT;
-- Post-commit:
--   ALTER TABLE exercises DROP CONSTRAINT IF EXISTS exercises_role_by_type_check;
--   ALTER TABLE exercises DROP COLUMN IF EXISTS role, DROP COLUMN IF EXISTS sub_target,
--     DROP COLUMN IF EXISTS true_max_effort, DROP COLUMN IF EXISTS needs_role_review;